INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('1', 'p1', 'SELLABLE', 'fc5', '4', '400') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('2','p2', 'UNFULFILLABLE', 'fc3', '5', '550') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('3','p3', 'INBOUND', 'fc4', '15','1800') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('4','p5', 'SELLABLE', 'fc1', '22', '3080') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('5','p10','INBOUND', 'fc5', '15', '2850') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('6','p1', 'UNFULFILLABLE', 'fc2', '10', '1000') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('7','p8', 'SELLABLE', 'fc1', '5', '850') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('8','p3', 'SELLABLE', 'fc2', '2', '240') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('9','p5', 'SELLABLE', 'fc5', '9', '1260') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('10','p3', 'SELLABLE', 'fc4', '25', '3000') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('11','p1', 'SELLABLE', 'fc5', '30', '3000') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('12','p5', 'UNFULFILLABLE', 'fc2', '7', '980') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('13','p7', 'UNFULFILLABLE', 'fc3', '4', '640') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('14','p8', 'INBOUND', 'fc1', '2', '340') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('15','p9', 'INBOUND', 'fc5', '17', '3060') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('16','p10','SELLABLE', 'fc4', '28', '5320') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('17','p9', 'SELLABLE', 'fc2', '10', '1800') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('18','p6', 'UNFULFILLABLE', 'fc3', '9', '1350') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('19','p9', 'INBOUND', 'fc1', '23', '4140') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('20','p2', 'INBOUND', 'fc4', '21', '2310') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('21','p4', 'UNFULFILLABLE', 'fc2', '19', '2470') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('22','p3', 'SELLABLE', 'fc5', '8', '960') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('23','p2', 'SELLABLE', 'fc2', '18', '1980') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('24','p5', 'UNFULFILLABLE', 'fc3', '13', '1820') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('25','p7', 'INBOUND', 'fc1', '7', '1120') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('26','p9', 'SELLABLE', 'fc4', '15', '2700') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('27','p1', 'INBOUND', 'fc5', '6', '600') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('28','p5', 'SELLABLE', 'fc2', '2', '280') ON CONFLICT DO NOTHING;
INSERT INTO products (id, product_id, status, fulfillment_center, quantity, price) VALUES ('29','p6', 'UNFULFILLABLE', 'fc1', '6', '900') ON CONFLICT DO NOTHING;

